apiVersion: apps/v1
kind: Deployment

metadata:
  name: python-app

spec:
  replicas: 3

  selector:
    matchLabels:
      app: python-app

  template:
    metadata:
      labels:
        app: python-app

    spec:
      containers:
        - name: python-app
          image: mohammadrezabazarjani/python-app:3ab3630374ebd33469a7121f82bb9765983404d5
          ports:
            - containerPort: 5000